Storybook update
MyOnlineStore/bricks pull request #595
Opened 2020-08-28 09:38 UTC by CarloPalinckx

### This PR:

[issue description]
-- or --
resolves #[resolved issue number]

**Breaking changes** 🔥
- None

**Backwards compatible additions** ✨
- None

**Bugfixes/Changed internals** 🎈
- Storybook was update to v6
- Slightly rewrote a few stories to support the new controls API

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2020-08-28 11:43 UTC, hborghols commented on packages/components/src/components/ScrollBox/style.tsx
> +/* overflow: hidden; */
Comments

2020-08-28 11:44 UTC, hborghols commented on packages/components/src/components/ScrollBox/style.tsx
> +    .simplebar-vertical .simplebar-scrollbar {
Are the changes in this file necessary for storybook?

2020-08-28 11:48 UTC, hborghols commented on package.json
> +    "@storybook/react": "^6.0.20",
Apparently we don't need @types/storybook__react anymore: https://www.npmjs.com/package/@types/storybook__react

2020-08-28 11:50 UTC, hborghols approved these changes
Approved with a few comments 🙂

2020-08-28 11:53 UTC, CarloPalinckx commented on packages/components/src/components/ScrollBox/style.tsx
> +    .simplebar-vertical .simplebar-scrollbar {
Ah whoops, initially thought I had to upgrade simplebar because of some core-js incompatibility, but I fixed that some other way. I'll revert this

2020-08-28 11:54 UTC, hborghols requested changes
Actually unapproved 😛, what is happening with the scrollbox? This happens in FF when loading the story (I'm not scrolling to be clear, it's scrolling on its own):

![scrollbox](https://user-images.githubusercontent.com/23050817/91558062-e43d9100-e935-11ea-9e8f-5ead4f72d8cb.gif)

2020-09-01 09:09 UTC, CarloPalinckx commented
@hborghols I have expelled the ghosts from the Scrollbox

2020-09-01 09:19 UTC, hborghols approved these changes

2020-09-01 09:19 UTC, merged