feat: Added hook to lock body scroll
MyOnlineStore/bricks pull request #613
Opened 2021-01-20 16:24 UTC by Dreamdealer

### This PR:

**Backwards compatible additions** ✨
- Added a hook to disable body scrolling
- Implemented the hook in Modal component

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2021-01-21 10:06 UTC, CarloPalinckx requested changes

2021-01-21 10:06 UTC, CarloPalinckx commented on packages/components/src/components/Modal/index.tsx
> +    lockBodyScroll?: boolean;
Maybe we could make this default behaviour rather than a prop? Or maybe default it to true? I think this would benefit overal UX platform wide.

2021-01-25 10:10 UTC, Dreamdealer commented on packages/components/src/components/Modal/index.tsx
> +    lockBodyScroll?: boolean;
I will ask UX about this idea.

2021-01-25 12:47 UTC, CarloPalinckx approved these changes

2021-01-25 12:48 UTC, merged