feat: Added new FileInput component
MyOnlineStore/bricks pull request #622
Opened 2021-04-28 08:28 UTC by Dreamdealer

### This PR:

**Backwards compatible additions** ✨
- New FileInput component

**Checklist** 🛡
- [ ] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [ ] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [ ] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2021-04-28 11:09 UTC, CarloPalinckx requested changes

2021-04-28 11:09 UTC, CarloPalinckx commented on packages/components/src/components/FileInput/index.tsx
> +            {props.feedback && props.feedback.message !== '' && (
You can use a conditional operator here

2021-04-28 11:09 UTC, CarloPalinckx commented on packages/components/src/components/FileInput/UploadPlaceholder.tsx
> +                <Icon icon={<CloudUploadIcon />} size="large" />
maybe there should be a theme variable to set the color of the icon

2021-04-28 11:09 UTC, CarloPalinckx commented on packages/components/src/components/FileInput/UploadPlaceholder.tsx
> +                        <>Drop your file here</>
These 2 texts should be pulled from props. Otherwise, they can't be translated 🙂

2021-04-29 07:55 UTC, Dreamdealer commented on packages/components/src/components/FileInput/index.tsx
> +const TextField: FC<PropsType> = props => {
I totally did not copy this from the TextField component 😬

2021-04-29 08:11 UTC, Dreamdealer commented on packages/components/src/components/FileInput/UploadPlaceholder.tsx
> +                <Icon icon={<CloudUploadIcon />} size="large" />
That's part of another PR

2021-04-29 11:09 UTC, CarloPalinckx requested changes
last small nit

2021-04-29 11:09 UTC, CarloPalinckx commented on packages/components/src/components/FileInput/index.tsx
> +    translations: {
I wouldn't nest these in a translations prop, since they in theory don't have to be translations but rather just "content". Also, maybe we could also support ReactNode here so people are free to drop in whatever they want

2021-04-29 11:47 UTC, CarloPalinckx requested changes

2021-04-29 11:47 UTC, CarloPalinckx commented on packages/components/src/components/FileInput/index.tsx
> +        dropOrBrowse: ReactNode;
```tsx
<FileInput 
  placeholders={{
     dropOrBrowser: '',
     dropHere: '',
  }}
/>
```
I'm still a little hung up on these, they feel a bit specific. That might get annoying when working with it IMO, have you considered something like:

```tsx
<FileInput  placeholder="" dragPlaceholder="" />
```

Which might be a bit more inline of other components that have similar props like the Select, which has a `placeholder` and an `emptyText` prop

2021-04-29 11:59 UTC, CarloPalinckx approved these changes

2021-04-29 12:40 UTC, merged