feat: Added new ColorField component
MyOnlineStore/bricks pull request #643
Opened 2021-05-31 10:51 UTC by Dreamdealer

### This PR:

**Backwards compatible additions** ✨
- Added new ColorField component

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2021-05-31 12:53 UTC, CarloPalinckx requested changes

2021-05-31 12:53 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +type OmittedKeys = 'onChange' | 'value' | 'prefix';
You only have to Omit `prefix` here since you don't have to override the types of onChange en value since they are the same for TextField as ColorField

2021-05-31 12:53 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +            <ColorDrop color={`#${displayValue}`} style={{ marginRight: '12px' }} />
Prefer a Box over inline styles

2021-05-31 12:53 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +                    if (ref && props.extractRef !== undefined) props.extractRef(ref);
Nit: Could this be multiline? 👼

2021-05-31 12:53 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +    const [displayValue, setDisplayValue] = useState(props.value);
I don't think you need state here? Since this is a controlled component you can use props.value instead right?

2021-06-02 08:11 UTC, Dreamdealer commented on packages/components/src/components/ColorField/index.tsx
> +                    if (ref && props.extractRef !== undefined) props.extractRef(ref);
Sure. This came from the copy/paste from CurrencyField. I'll fix it in that file too.

2021-06-02 13:57 UTC, CarloPalinckx requested changes

2021-06-02 13:57 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +type PropsType = Pick<TextFieldPropsType, Exclude<keyof TextFieldPropsType, OmittedKeys>> & {
You can remove the 
```
& {
    value: string;
    onChange(value: string): void;
};
```
here since we are Picking the props from `TextFieldPropsType` which also have these 2 defined with strings

2021-06-03 07:22 UTC, CarloPalinckx approved these changes

2021-06-03 07:22 UTC, merged