chore: Added tests to ColorInput component
MyOnlineStore/bricks pull request #652
Opened 2021-06-07 13:37 UTC by Dreamdealer

### This PR: 

Adds tests.

2021-06-07 14:07 UTC, CarloPalinckx requested changes

2021-06-07 14:07 UTC, CarloPalinckx commented on packages/components/src/components/ColorField/index.tsx
> +    colorInputContainer = 'color-input-container',
These cannot be static like they are in canopy since you have to be able to pass in a data-testid through props. Would be nice if the id passed in through props is that one that currently corresponds with `colorInputField` so that you can directly simulate on that in tests. The other ones can be a composite of the prop plus a suffix (`foo-reset`) for instance

2021-06-07 14:18 UTC, Dreamdealer commented on packages/components/src/components/ColorField/index.tsx
> +    colorInputContainer = 'color-input-container',
Yes. I make that.

2021-06-08 08:12 UTC, CarloPalinckx approved these changes

2021-06-08 08:13 UTC, merged