fix: Fixed z-indexing issues and added a close callback to window
MyOnlineStore/bricks pull request #667
Opened 2021-07-12 11:34 UTC by Dreamdealer

### This PR:

Fixed z-indexing issues and added a close callback to window. Also added box props to ColorPicker component.

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2021-07-13 10:45 UTC, CarloPalinckx requested changes

2021-07-13 10:45 UTC, CarloPalinckx commented on packages/components/src/components/TextField/index.tsx
> +                <Box position={props.onClear && props.value !== '' ? 'relative' : undefined} width="100%">
Why was this added? 🤔

2021-07-13 10:51 UTC, Dreamdealer commented on packages/components/src/components/TextField/index.tsx
> +                <Box position={props.onClear && props.value !== '' ? 'relative' : undefined} width="100%">
The position relative is only used for the pos:abs that the reset/clear button uses. And since the reset button is not used in the colorpicker and that is what causes the z-index issues, i choose to only apply the position relative if it is needed.

2021-07-15 12:42 UTC, CarloPalinckx approved these changes

2021-07-15 12:42 UTC, merged