feat!: CASH-2704 - Replaced AssetProvider with svg sprite
MyOnlineStore/bricks pull request #720
Opened 2021-12-24 13:54 UTC by woutsluiter

BREAKING CHANGE: Removed useAssetLoader from exports

Implemented svg sprites in `Icon` and added a script to generate a sprite with a cache busting hash. This output can be uploaded to the CDN. This at least fixes our [icon bug](https://myonlinestore.atlassian.net/browse/CASH-2704), but there are a few improvements I can think of we can implement in the future:

- automatic upload to CDN
- automatic hash change in the SpriteProvider

**Breaking changes** 🔥
- Removed `useAssetLoader` from exports

**Backwards compatible additions** ✨
- Added `SpriteProvider` to `BricksProvider` for lazy loading the sprite from CDN

**Bugfixes/Changed internals** 🎈
- `Icon` references icons from a sprite
- Added a script to generate a new svg sprite

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [ ] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2021-12-24 14:10 UTC, CarloPalinckx requested changes

2021-12-24 14:10 UTC, CarloPalinckx commented on scripts/svg-sprite.js
> +        // id: {
Can this be removed?

2021-12-24 14:22 UTC, CarloPalinckx approved these changes

2022-01-03 13:53 UTC, hborghols approved these changes

2022-01-03 13:53 UTC, merged