chore: Untheme ImageRadio
MyOnlineStore/bricks pull request #773
Opened 2022-08-17 07:14 UTC by KuiseRapper

### This PR:

**Bugfixes/Changed internals** 🎈
- Component ImageRadio no longer uses Theme

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

2022-08-17 14:36 UTC, CarloPalinckx submitted a review, later dismissed

2022-08-17 14:36 UTC, CarloPalinckx commented on packages/components/src/components/ImageRadio/style.tsx
> +                return `box-shadow: 0 0 0 2px ${colors.red300} inset, 0px 0px 0px 4px ${rgba(colors.red100, 0.875)}`;
All these box shadow could use a `;` within the string to close the css rule. This would break if we were to add a css rule onder this code block

2022-08-18 08:17 UTC, KuiseRapper commented on packages/components/src/components/ImageRadio/style.tsx
> +                return `box-shadow: 0 0 0 2px ${colors.red300} inset, 0px 0px 0px 4px ${rgba(colors.red100, 0.875)}`;
under*

2022-08-19 07:46 UTC, woutsluiter approved these changes
Found a weird Johan leftover, but looks good otherwise.

2022-08-19 07:46 UTC, woutsluiter commented on packages/components/src/components/ImageRadio/style.tsx
> +                return `box-shadow: 0 0 0 2px ${colors.red300} inset, 0px 0px 0px 4px ${rgba(colors.red100, 0.875)};`;
I guess this is one of those Johan things, but this just doesn't make sense. `box-shadow` is defined twice in this component, one overwriting the other... sometimes. You could consider refactoring this here, but a separate PR would be fine as well.

2022-08-23 12:18 UTC, CarloPalinckx requested changes

2022-08-23 12:18 UTC, CarloPalinckx commented on packages/components/src/components/ImageRadio/style.tsx
>              if (checked && disabled) {
this `checked` is redundant since you already check if `checked`

2022-08-23 12:18 UTC, CarloPalinckx commented on packages/components/src/components/ImageRadio/style.tsx
>              if (checked && disabled) {
same here

2022-08-23 12:18 UTC, CarloPalinckx commented on packages/components/src/components/ImageRadio/style.tsx
> +            if (disabled && checked) {
same here

2022-08-23 13:07 UTC, merged